# sudo python3 installer.py
import os, time, sys

os.system('clear')
time.sleep(5)
print("Kalau di tanya Y/n jawab aja Y")
time.sleep(5)
print("kalau muncul dialog pencet enter aja ya")
time.sleep(5)
print("otw bos ku")
time.sleep(5)
os.system('clear')
os.system('sudo apt update -y && sudo apt upgrade -y') 
os.system('sudo apt install nodejs -y')
os.system('sudo apt install npm -y')
os.system('sudo apt install python3 -y')
os.system('sudo apt install python3-pip -y')
os.system('npm i hpack')
os.system('npm i colors')
os.system('npm i user-agents')
os.system('npm i axios header-generator random-useragent readline-sync') 
os.system('npm i node-fetch')
os.system('wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.0/install.sh | bash')
os.system('source ~/.bashrc')
os.system('nvm install 20')
os.system('nvm use 20')
os.system('npm i gradient-string')
os.system('npm i random-useragent')
os.system('npm install puppeteer puppeteer-extra puppeteer-extra-plugin-stealth async')
os.system('sudo apt update -y && sudo apt install ca-certificates fonts-liberation libappindicator3-1 libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils -y')
os.system('npm i net fs url hpack path colors child_process http2 random-referer request axios tls crypto header-generator user-agents cluster fake-useragent randomstring string-random puppeteer puppeteer-extra puppeteer-extra-plugin-stealth async hpack')
os.system('pip install node-fetch') 
os.system('npm i sockopt') 
os.system('npm i cheerio')
os.system('pip install colorama request')
time.sleep(1)
os.system('clear')
time.sleep(5)
print("well done")
time.sleep(5)
sys.exit()